DROP TABLE IF EXISTS TB_CAT_META;
CREATE TABLE TB_CAT_META
(
    category_id INT PRIMARY KEY,
    category_name VARCHAR(30)
);

DROP TABLE IF EXISTS TB_CAT_TOP;
CREATE TABLE TB_CAT_TOP
(
    sub_category_id INT PRIMARY KEY,
    sub_category_name VARCHAR(30)
);

DROP TABLE IF EXISTS TB_CAT_OTR;
CREATE TABLE TB_CAT_OTR
(
    sub_category_id INT PRIMARY KEY,
    sub_category_name VARCHAR(30)
);
